<?php

namespace App\Form;

use App\Entity\ShopSearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ShopSearchFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('shopName', null, [
                'required'=>true,
                'attr'=>[
                    'placeholder'=>'Nom de la boutique'
                ]
            ])
            ->add('shopLocation', null, [
                'required'=>true,
                'attr'=>[
                    'placeholder'=>'Ville, commune, quartier'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ShopSearch::class,
            'method'=>'GET',
            'csrf_protection'=>false
        ]);
    }
    public function getBlockPrefix(): string
    {
        return ""; // TODO: Change the autogenerated stub
    }
}
