<?php

namespace App\Form;

use App\Entity\Stock;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StockFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('quantity', NumberType::class, [
                'attr'=>['placeholder'=>'Ex: 250'],
                'required'=>true
            ])
            ->add('size', ChoiceType::class, [
                'required'=>true,
                'choices'=>[
                    'Jeans-Pantalons-Chinos'=>[
                        'M Long'=>'M Long',
                        'L Long'=>'L Long',
                        'S Long'=>'S Long',
                        'XL Long'=>'XL Long',
                        '2XL Long'=>'2XL Long',
                        '32-34'=>'32-34',
                        '36-38'=>'36-38',
                        '40-42'=>'40-42',
                        '44-46'=>'44-46',
                        '48-50'=>'48-50',
                        '52'=>'52',
                        '52-54'=>'52-54',
                        '58'=>'58',
                    ],
                    'Taille T-Shirts'=>[
                        'M tall'=>'M tall',
                        'M Long'=>'M Long',
                        'L Tall'=>'L Tall',
                        'L Long'=>'L Long',
                        'S Long'=>'S Long',
                        'S Tall'=>'S Tall',
                        'XL Long'=>'XL Long',
                        'XL Tall'=>'XL Tall',
                        '2XL Long'=>'2XL Long',
                        '2XL Tall'=>'2XL Tall',
                        '3XL Regular'=>'3XL Regular',
                        '4XL Regular'=>'4XL Regular',
                        '5XL Regular'=>'5XL Regular',
                        'FR 30'=>'FR 30',
                        'FR 32'=>'FR 32',
                        'FR 32-34'=>'FR 32-34',
                        'FR 36'=>'FR 36',
                        'FR 36-38'=>'FR 36-38',
                        'FR 40'=>'FR 40',
                        'FR 40-42'=>'FR 40-42',
                        'FR 44'=>'FR 44',
                        'FR 44-46'=>'FR 44-46',
                        'FR 48'=>'FR 48',
                        'FR 48-50'=>'FR 48-50',
                        'FR 52'=>'FR 52',
                        'FR 52-54'=>'FR 52-54',
                        'FR 56-58'=>'FR 56-58',
                        'FR 58'=>'FR 58',
                        'EU 44'=>'EU 44',
                        'EU 46'=>'EU 46',
                        'EU 48'=>'EU 48',
                        'EU 50'=>'EU 50',
                        'EU 52'=>'EU 52',
                        'EU 54'=>'EU 54',
                        '3XS'=>'3XS',
                        '2XS'=>'2XS',
                        'XXS'=>'XXS',
                        'XS'=>'XS',
                        'S'=>'S',
                        'M'=>'M',
                        'L'=>'L',
                        'XL'=>'XL',
                        '2XL'=>'2XL',
                        'XXL'=>'XXL',
                        'XXXL'=>'XXXL',
                        '3XL'=>'3XL',
                        '4XL'=>'4XL',
                        '5XL'=>'5XL',
                        '6XL'=>'6XL',
                        'XS-S'=>'XS-S',
                        'L-XL'=>'L-XL',
                        '4X'=>'4X',
                    ],
                    'Tailles Chemises'=>[
                        'XS Long'=>'XS Long',
                        'M Long'=>'M Long',
                        'L Long'=>'L Long',
                        'S Long'=>'S Long',
                        'XL Long'=>'XL Long',
                        '2XL Long'=>'2XL Long',
                        '3XL Regular'=>'3XL Regular',
                        '3XL Long'=>'3XL Long',
                        '4XL Regular'=>'4XL Regular',
                        '5XL Regular'=>'5XL Regular',
                        '6XL Regular'=>'6XL Regular',
                        'FR 32'=>'FR 32',
                        'FR 32-34'=>'FR 32-34',
                        'FR 36'=>'FR 36',
                        'FR 36-38'=>'FR 36-38',
                        'FR 40'=>'FR 40',
                        'FR 40-42'=>'FR 40-42',
                        'FR 44'=>'FR 44',
                        'FR 44-46'=>'FR 44-46',
                        'FR 48'=>'FR 48',
                        'FR 48-50'=>'FR 48-50',
                        'FR 52'=>'FR 52',
                        'FR 52-54'=>'FR 52-54',
                        'FR 56-58'=>'FR 56-58',
                        'FR 58'=>'FR 58',
                        'EU 44'=>'EU 44',
                        'EU 46'=>'EU 46',
                        'EU 48'=>'EU 48',
                        'EU 50'=>'EU 50',
                        'EU 52'=>'EU 52',
                        'EU 54'=>'EU 54',
                        'Size 46'=>'Size 46',
                        'Size 48'=>'Size 48',
                        'Size 50'=>'Size 50',
                        'Size 52'=>'Size 52',
                        'Size 54'=>'Size 54',
                        '2XS'=>'2XS',
                        'XXS'=>'XXS',
                        'XS'=>'XS',
                        'S'=>'S',
                        'M'=>'M',
                        'L'=>'L',
                        'XL'=>'XL',
                        '2XL'=>'2XL',
                        'XXL'=>'XXL',
                        'XXXL'=>'XXXL',
                        '3XL'=>'3XL',
                        '4XL'=>'4XL',
                        'XXXXL'=>'XXXXL',
                        '5XL'=>'5XL',
                        '6XL'=>'6XL',
                        'XXXXXL'=>'XXXXXL',
                    ],
                    'Tailles Costumes-vestes'=>[
                        'FR 32-34'=>'FR 32-34',
                        'FR 36-38'=>'FR 36-38',
                        'FR 40-42'=>'FR 40-42',
                        'FR 44-46'=>'FR 44-46',
                        'FR 48-50'=>'FR 48-50',
                        'FR 52'=>'FR 52',
                        'FR 52-54'=>'FR 52-54',
                        'FR 58'=>'FR 58',
                        '2XS'=>'2XS',
                        'XS'=>'XS',
                        'S'=>'S',
                        'M'=>'M',
                        'L'=>'L',
                        'XL'=>'XL',
                        '2XL'=>'2XL',
                        'W26'=>'W26',
                        'W26 L30'=>'W26 L30',
                        'W26 L32'=>'W26 L32',
                        'W28 L30'=>'W28 L30',
                        'W28L32'=>'W28L32',
                        'W28 L32'=>'W28 L32',
                        'W30 L30'=>'W30 L30',
                        'W30L32'=>'W30L32',
                        'W30 L32'=>'W30 L32',
                        'W30 L34'=>'W30 L34',
                        'W30 L36'=>'W30 L36',
                        'W30 L38'=>'W30 L38',
                        'W31 L30'=>'W31 L30',
                        'W31 L32'=>'W31 L32',
                        'W32 L30'=>'W32 L30',
                        'W32L32'=>'W32L32',
                        'W32 L32'=>'W32 L32',
                        'W32 L34'=>'W32 L34',
                        'W32 L36'=>'W32 L36',
                        'W32 L38'=>'W32 L38',
                        'W32 Long'=>'W32 Long',
                        'W33 L30'=>'W33 L30',
                        'W33 L32'=>'W33 L32',
                        'W33 L34'=>'W33 L34',
                        'W34 L30'=>'W34 L30',
                        'W34 L32'=>'W34 L32',
                        'W34 L34'=>'W34 L34',
                        'W34 L36'=>'W34 L36',
                        'W34 L38'=>'W34 L38',
                        'W34L32'=>'W34L32',
                        'W34 Long'=>'W34 Long',
                        'W36 L30'=>'W36 L30',
                        'W36 L32'=>'W36 L32',
                        'W36 L34'=>'W36 L34',
                        'W36 L36'=>'W36 L36',
                        'W36 L38'=>'W36 L38',
                        'W36L32'=>'W36L32',
                        'W38 L32'=>'W38 L32',
                        'W38 L34'=>'W38 L34',
                        'W38 L36'=>'W38 L36',
                        'W38 L38'=>'W38 L38',
                        'W40 L30'=>'W40 L30',
                        'W40 L32'=>'W40 L32',
                        'W40 L34'=>'W40 L34',
                        'W40 L36'=>'W40 L36',
                        'W42 L30'=>'W42 L30',
                        'W42 L32'=>'W42 L32',
                        'W42 L34'=>'W42 L34',
                        'W42 L36'=>'W42 L36',
                        'W42 L38'=>'W42 L38',
                        'W44 L30'=>'W44 L30',
                        'W44 L32'=>'W44 L32',
                        'W44 L34'=>'W44 L34',
                        'W44 L36'=>'W44 L36',
                        'W44 L38'=>'W44 L38',
                        'W46 L30'=>'W46 L30',
                        'W46 L32'=>'W46 L32',
                        'W46 L34'=>'W46 L34',
                        'W28'=>'W28',
                        'W30'=>'W30',
                        'W32'=>'W32',
                        'W34'=>'W34',
                        'W36'=>'W36',
                        'W38'=>'W38',
                        'UK 12-14'=>'UK 12-14',
                        'UK 14-16'=>'UK 14-16',
                        '46'=>'46',
                        '48'=>'48',
                        '50'=>'50',
                        '52'=>'52',
                        '54'=>'54',
                        '81'=>'81',
                        '86'=>'86',
                        '91'=>'91',
                        '96'=>'96',
                        '102'=>'102',
                        '107'=>'107',
                        '112'=>'112',
                        '117'=>'117',
                        'Chest 32 Regular'=>'Chest 32 Regular',
                        'Chest 34 Regular'=>'Chest 34 Regular',
                        'Chest 36 Short'=>'Chest 36 Short',
                        'Chest 36 Regular'=>'Chest 36 Regular',
                        'Chest 36 Long'=>'Chest 36 Long',
                        'Chest 38 Short'=>'Chest 38 Short',
                        'Chest 38 Regular'=>'Chest 38 Regular',
                        'Chest 38 Long'=>'Chest 38 Long',
                        'Chest 38 Extra Long'=>'Chest 38 Extra Long',
                        'Chest 40 Short'=>'Chest 40 Short',
                        'Chest 40 Regular'=>'Chest 40 Regular',
                        'Chest 40 Long'=>'Chest 40 Long',
                        'Chest 40 Extra Long'=>'Chest 40 Extra Long',
                        'Chest 42 Short'=>'Chest 42 Short',
                        'Chest 42 Regular'=>'Chest 42 Regular',
                        'Chest 42 Long'=>'Chest 42 Long',
                        'Chest 42 Extra Long'=>'Chest 42 Extra Long',
                        'Chest 44 Short'=>'Chest 44 Short',
                        'Chest 44 Regular'=>'Chest 44 Regular',
                        'Chest 44 Long'=>'Chest 44 Long',
                        'Chest 44 Extra Long'=>'Chest 44 Extra Long',
                        'Chest 46 Regular'=>'Chest 46 Regular',
                        'Chest 46 Long'=>'Chest 46 Long',
                        'Chest 46 Extra Long'=>'Chest 46 Extra Long',
                        'Chest 48 Regular'=>'Chest 48 Regular',
                        'Chest 48 Long'=>'Chest 48 Long',
                        'Chest 48 Extra Long'=>'Chest 48 Extra Long',
                        'Chest 50 Regular'=>'Chest 50 Regular',
                        'Chest 50 Long'=>'Chest 50 Long',
                        'Chest 52 Regular'=>'Chest 52 Regular',
                        'Chest 52 Long'=>'Chest 52 Long',
                        'Chest 54 Long'=>'Chest 54 Long',
                        'Chest 34'=>'Chest 34',
                        'Chest 36'=>'Chest 36',
                        'Chest 38'=>'Chest 38',
                        'Chest 40'=>'Chest 40',
                        'Chest 42'=>'Chest 42',
                        'Chest 44'=>'Chest 44',
                        'Chest 46'=>'Chest 46',
                        'W28S'=>'W28S',
                        'W34S'=>'W34S',
                        'W34R'=>'W34R',
                        'W32R'=>'W32R',
                        'W32S'=>'W32S',
                        'W30S'=>'W30S',
                        'W30R'=>'W30R',
                        'W36R'=>'W36R',
                    ],
                    'Tailles Chaussettes'=>[
                        'EU 35-38'=>'EU 35-38',
                        'EU 39-42'=>'EU 39-42',
                        'No Size'=>'No Size',
                        'One Size'=>'One Size',
                        'S'=>'S',
                        'M'=>'M',
                        'L'=>'L',
                        'XL'=>'XL',
                        'S-M'=>'S-M',
                        'M-L'=>'M-L',
                        'L-XL'=>'L-XL',
                        'UK 3-5'=>'UK 3-5',
                        'UK 4-8'=>'UK 4-8',
                        'UK 5.5-8'=>'UK 5.5-8',
                        'UK 5-7.5'=>'UK 5-7.5',
                        'UK 6-8.5'=>'UK 6-8.5',
                        'UK 6-9'=>'UK 6-9',
                        'UK 7.5-9.5'=>'UK 7.5-9.5',
                        'UK 8.5-11'=>'UK 8.5-11',
                        'UK 9-11'=>'UK 9-11',
                        'UK 9-13'=>'UK 9-13',
                        'UK 6-8'=>'UK 6-8',
                        'EU 37'=>'EU 37',
                        'EU 43'=>'EU 43'
                    ],
                    'Tailles Chaussures-Baskets'=>[
                        '38.5'=>'38.5',
                        '42 2/3'=>'42 2/3',
                        '44'=>'44',
                        '44 2/3'=>'44 2/3',
                        '44.5'=>'44.5',
                        '45'=>'45',
                        '45 1/3'=>'45 1/3',
                        '45.5'=>'45.5',
                        '46'=>'46',
                        '46 2/3'=>'46 2/3',
                        '46. 5'=>'46. 5',
                        '46.5'=>'46.5',
                        '47'=>'47',
                        '47 1/3'=>'47 1/3',
                        '47.5'=>'47.5',
                        '48'=>'48',
                        '48.5'=>'48.5',
                        '48 2/3'=>'48 2/3',
                        '49'=>'49',
                        '35'=>'35',
                        '36'=>'36',
                        '36 2/3'=>'36 2/3',
                        '36.5'=>'36.5',
                        '37'=>'37',
                        '37 1/3'=>'37 1/3',
                        '37.5'=>'37.5',
                        '38'=>'38',
                        '38 2/3'=>'38 2/3',
                        '39'=>'39',
                        '39 1/3'=>'39 1/3',
                        '39.5'=>'39.5',
                        '40'=>'40',
                        '40 2/3'=>'40 2/3',
                        '40.5'=>'40.5',
                        '41'=>'41',
                        '41 1/3'=>'41 1/3',
                        '41.5'=>'41.5',
                        '42'=>'42',
                        '42.5'=>'42.5',
                        '43'=>'43',
                        '43 1/3'=>'43 1/3',
                        '43.5'=>'43.5',
                    ],
                    'TAILLE UNIQUE'=>'TAILLE UNIQUE',
                    'AUTRE'=>'AUTRE'
                ]
            ])
            ->add('type', ChoiceType::class, [
                'required'=>true,
                'choices'=>[
                    'ACCESSOIRES'=>[
                        'Accessoires de mode'=>'Accessoires de mode',
                        'Bonnets'=>'Bonnets',
                        'Bracelets'=>'Bracelets',
                        'Ceintures'=>'Ceintures',
                        'Colliers'=>'Colliers',
                        'Echarpes-Foulards'=>'Echarpes-Foulards',
                        'Gants'=>'Gants',
                        'Lunettes de Soleil'=>'Lunettes de Soleil',
                        'Montres'=>'Montres',
                        'Portefeuilles'=>'Portefeuilles',
                        'Sacs Banane'=>'Sacs Banane',
                        'Sacs-Sacoches'=>'Sacs-Sacoches',
                        'Bijoux'=>'Bijoux',
                        'Casquettes/Chapeaux'=>'Casquettes',
                        'Cravates'=>'Cravates',
                    ],
                    'CHAUSSURES'=>[
                        'Baskets Basses'=>'Baskets Basses',
                        'Baskets Montantes'=>'Baskets Montantes',
                        'Bottes - Boots'=>'Bottes - Boots',
                        'Chelsea Boots'=>'Chelsea Boots',
                        'Chaussures'=>'Chaussures',
                        'Claquettes - Sandales'=>'Claquettes - Sandales',
                        'Tongs'=>'Tongs',
                        'Mocassins'=>'Mocassins',
                        'Sandales'=>'Sandales'
                    ],
                    'VÊTEMENTS'=>[
                        'Blousons-Vestes'=>'Blousons-Vestes',
                        'Chemises'=>[
                            'Chemises en jean'=>'Chemises en jean',
                            'Chemises a carreaux'=>'Chemises a carreaux',
                            'Chemises imprimées'=>'Chemises imprimées',
                            'Chemises unies'=>'Chemises unies',
                            'Chemises Casual'=>'Chemises Casual',
                            'Chemises à manches courtes'=>'Chemises à manches courtes'
                        ],
                        'Costûmes'=>[
                            'Blazers'=>'Blazers',
                            'Cosutmes Slim'=>'Cosutmes Slim',
                            'Costumes De Mariage'=>'Costumes De Mariage',
                            'Costumes Trois Pièces'=>'Costumes Trois Pièces',
                            'Gilets'=>'Gilets',
                            'Pantalon De Costume'=>'Pantalon De Costume',
                        ],
                        'Débardeurs'=>'Débardeurs',
                        'Jeans'=>[
                            'Jeans Skinny'=>'Jeans Skinny',
                            'Jeans Fuselés'=>'Jeans Fuselé',
                            'Jeans Slim'=>'Déchirés',
                            'Jeans Blancs'=>'Jeans Blancs',
                            'Jeans Clairs Délavés'=>'Jeans Clairs Délavés',
                            'Jeans Super Skinny'=>'Jeans Super Skinny'
                        ],
                        'Joggings'=>'Joggings',
                        'Pantalons & Chinos'=>[
                            'Pantalons Chinos'=>'Pantalons Chinos',
                            'Pantalons en velours côtelé'=>'Pantalons en velours côtelé',
                            'Pantalons Skinny'=>'Pantalons Skinny',
                            'Pantalons Cargo'=>'Pantalons Cargo',
                            'Pantalons Courts'=>'Pantalons Courts'
                        ],
                        'Pulls'=>[
                            'Pulls à Col roulé'=>'Pulls à Col roulé',
                            'Pulls'=>'Pulls',
                            'Gilets'=>'Gilets',
                            'Gros Pulls'=>'Gros Pulls',
                            'Pulls Torsadés'=>'Pulls Torsadés',
                            'Pulls Unis'=>'Pulls Unis',
                            'Pulls En Laine'=>'Pulls En Laine',
                            'Pulls Col V'=>'Pulls Col V',
                            'Pulls Ras de Cou'=>'Pulls Ras de Cou',
                            'Pulls à Rayures'=>'Pulls à Rayures',
                        ],
                        'Polos'=>'Polos',
                        'Shorts'=>[
                            'Bermuda'=>'Bermuda',
                            'Shorts En Jeans'=>'Shorts En Jeans',
                            'Shorts Ajustés'=>'Shorts Ajustés',
                            'Shorts Chino'=>'Shorts Chino'
                        ],
                        'Sous-Vêtements'=>'Sous-Vêtements',
                        'Survêtements'=>'Survêtements',
                        'Robes-Jupes'=>'Robes-Jupes',
                        'Sweats-Pulls'=>'Sweats-Pulls',
                        'T-shirts'=>[
                            'T-shirts à rayures'=>'T-shirts à rayures',
                            'T-shirts imprimés'=>'T-shirts imprimés',
                            'T-shirts unis'=>'T-shirts unis',
                            'T-shirts à encolure dégagée'=>'T-shirts à encolure dégagée',
                            'T-shirts ras du cou'=>'T-shirts ras du cou',
                            'T-shirts col V'=>'T-shirts col V'
                        ],
                    ]
                ]
            ])
            ->add('category', ChoiceType::class, [
                'required'=>true,
                'choices'=>[
                    'ACCESSOIRES'=>'ACCESSOIRES',
                    'CHAUSSURES'=>'CHAUSSURES',
                    'VÊTEMENTS'=>'VÊTEMENTS',
                ]
            ])
            ->add('brand', ChoiceType::class, [
                'required'=>true,
                'choices'=>[
                    "Aarhon"=>"Aarhon",
                    "adidas"=>"adidas",
                    "Armita"=>"Armita",
                    "Asics"=>"Asics",
                    "Capslab"=>"Capslab",
                    "BOSS"=>"BOSS",
                    "Calvin Klein"=>"Calvin Klein",
                    "Champion"=>"Champion",
                    "Classic Series"=>"Classic Series",
                    "Diesel"=>"Diesel",
                    "Ellesse"=>"Ellesse",
                    "Fila"=>"Fila",
                    "Final Club"=>"Final Club",
                    "Frilivin"=>"Frilivin",
                    "Emporio Armani"=>"Emporio Armani",
                    "Guess"=>"Guess",
                    "HUGO"=>"HUGO",
                    "Jack And Jones"=>"Jack And Jones",
                    "Le Coq Sportif"=>"Le Coq Sportif",
                    "New Balance"=>"New Balance",
                    "New Era"=>"New Era",
                    "Nike"=>"Nike",
                    "Puma"=>"Puma",
                    "Ray-Ban"=>"Ray-Ban",
                    "Reebok"=>"Reebok",
                    "Replay"=>"Replay",
                    "Sergio Tacchini"=>"Sergio Tacchini",
                    "Teddy Smith"=>"Teddy Smith",
                    "The North Face"=>"The North Face",
                    "Tommy Hilfiger"=>"Tommy Hilfiger",
                    "Uniplay"=>"Uniplay",
                    "Urban Classics"=>"Urban Classics",
                    "Vans"=>"Vans",
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stock::class,
        ]);
    }
}
